python2_tests.erl:113: The variable _ can never match since previous clauses completely covered the type 'false'
python2_tests.erl:115: The variable _ can never match since previous clauses completely covered the type 'false'
python2_tests.erl:116: The variable _ can never match since previous clauses completely covered the type 'false'
python3_tests.erl:113: The variable _ can never match since previous clauses completely covered the type 'false'
python3_tests.erl:115: The variable _ can never match since previous clauses completely covered the type 'false'
python3_tests.erl:116: The variable _ can never match since previous clauses completely covered the type 'false'
python_options_tests.erl:56: The created fun has no local return
python_options_tests.erl:56: The created fun has no local return
python_options_tests.erl:57: The call python_options:parse([{'buffer_size','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:80: The created fun has no local return
python_options_tests.erl:80: The created fun has no local return
python_options_tests.erl:81: The call python_options:parse([{'compressed','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:105: The created fun has no local return
python_options_tests.erl:105: The created fun has no local return
python_options_tests.erl:106: The call python_options:parse([{'start_timeout','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:118: The created fun has no local return
python_options_tests.erl:118: The created fun has no local return
python_options_tests.erl:119: The call python_options:parse([{'call_timeout','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:128: The created fun has no local return
python_options_tests.erl:128: The created fun has no local return
python_options_tests.erl:133: The created fun has no local return
python_options_tests.erl:133: The created fun has no local return
python_options_tests.erl:134: The call python_options:parse([{'env','invalid_env'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:191: The created fun has no local return
python_options_tests.erl:191: The created fun has no local return
python_options_tests.erl:192: The call python_options:parse([{'python','not_string'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:353: The created fun has no local return
python_options_tests.erl:353: The created fun has no local return
python_options_tests.erl:355: The call python_options:parse([{'python_path','invalid_path'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:359: The created fun has no local return
python_options_tests.erl:359: The created fun has no local return
python_options_tests.erl:362: The created fun has no local return
python_options_tests.erl:362: The created fun has no local return
python_options_tests.erl:377: The created fun has no local return
python_options_tests.erl:377: The created fun has no local return
python_options_tests.erl:378: The call python_options:parse(['unknown',...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
ruby18_tests.erl:116: The variable _ can never match since previous clauses completely covered the type 'false'
ruby18_tests.erl:119: The variable _ can never match since previous clauses completely covered the type 'false'
ruby18_tests.erl:120: The variable _ can never match since previous clauses completely covered the type 'false'
ruby19_tests.erl:116: The variable _ can never match since previous clauses completely covered the type 'false'
ruby19_tests.erl:119: The variable _ can never match since previous clauses completely covered the type 'false'
ruby19_tests.erl:120: The variable _ can never match since previous clauses completely covered the type 'false'
ruby_options_tests.erl:56: The created fun has no local return
ruby_options_tests.erl:56: The created fun has no local return
ruby_options_tests.erl:57: The call ruby_options:parse([{'buffer_size','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:80: The created fun has no local return
ruby_options_tests.erl:80: The created fun has no local return
ruby_options_tests.erl:81: The call ruby_options:parse([{'compressed','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:105: The created fun has no local return
ruby_options_tests.erl:105: The created fun has no local return
ruby_options_tests.erl:106: The call ruby_options:parse([{'start_timeout','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:118: The created fun has no local return
ruby_options_tests.erl:118: The created fun has no local return
ruby_options_tests.erl:119: The call ruby_options:parse([{'call_timeout','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:128: The created fun has no local return
ruby_options_tests.erl:128: The created fun has no local return
ruby_options_tests.erl:133: The created fun has no local return
ruby_options_tests.erl:133: The created fun has no local return
ruby_options_tests.erl:134: The call ruby_options:parse([{'env','invalid_env'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:196: The created fun has no local return
ruby_options_tests.erl:196: The created fun has no local return
ruby_options_tests.erl:197: The call ruby_options:parse([{'ruby','not_string'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:358: The created fun has no local return
ruby_options_tests.erl:358: The created fun has no local return
ruby_options_tests.erl:360: The call ruby_options:parse([{'ruby_lib','invalid_path'},...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
ruby_options_tests.erl:364: The created fun has no local return
ruby_options_tests.erl:364: The created fun has no local return
ruby_options_tests.erl:367: The created fun has no local return
ruby_options_tests.erl:367: The created fun has no local return
ruby_options_tests.erl:382: The created fun has no local return
ruby_options_tests.erl:382: The created fun has no local return
ruby_options_tests.erl:383: The call ruby_options:parse(['unknown',...]) breaks the contract (Options::options()) -> {'ok',#ruby_options{}} | {'error',Reason::term()}
