python_options_tests.erl:60: The created fun has no local return
python_options_tests.erl:60: The created fun has no local return
python_options_tests.erl:61: The call python_options:parse([{'compressed','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:85: The created fun has no local return
python_options_tests.erl:85: The created fun has no local return
python_options_tests.erl:86: The call python_options:parse([{'start_timeout','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:98: The created fun has no local return
python_options_tests.erl:98: The created fun has no local return
python_options_tests.erl:99: The call python_options:parse([{'call_timeout','invalid'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:108: The created fun has no local return
python_options_tests.erl:108: The created fun has no local return
python_options_tests.erl:113: The created fun has no local return
python_options_tests.erl:113: The created fun has no local return
python_options_tests.erl:114: The call python_options:parse([{'env','invalid_env'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:151: The created fun has no local return
python_options_tests.erl:151: The created fun has no local return
python_options_tests.erl:152: The call python_options:parse([{'python','not_string'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:264: The created fun has no local return
python_options_tests.erl:264: The created fun has no local return
python_options_tests.erl:266: The call python_options:parse([{'python_path','invalid_path'},...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_options_tests.erl:270: The created fun has no local return
python_options_tests.erl:270: The created fun has no local return
python_options_tests.erl:273: The created fun has no local return
python_options_tests.erl:273: The created fun has no local return
python_options_tests.erl:288: The created fun has no local return
python_options_tests.erl:288: The created fun has no local return
python_options_tests.erl:289: The call python_options:parse(['unknown',...]) breaks the contract (Options::options()) -> {'ok',#python_options{}} | {'error',Reason::term()}
python_tests.erl:175: Cons will produce an improper list since its 2nd argument is 1
python_tests.erl:176: Cons will produce an improper list since its 2nd argument is nonempty_improper_list(2 | 3,4)
python_tests.erl:177: Cons will produce an improper list since its 2nd argument is 'tail'
