Erlang port protocol
====================

Setup test modules, classes and functions:

    >>> import os
    >>> from erlport.erlproto import Port, Protocol
    >>> from erlport.erlterms import Atom, encode, decode

    >>> class TestProtocol(Protocol):
    ...
    ...     def handle_test(self, value="test"):
    ...         return value
    ...
    ...     def handle_crash(self):
    ...         raise ValueError("error")

    >>> def get_test_proto(proto, packet=1, compressed=False):
    ...     def test(request):
    ...         r, out_d = os.pipe()
    ...         in_d, w = os.pipe()
    ...         port = Port(packet, compressed=compressed, descriptors=(r, w))
    ...         port2 = Port(packet, compressed=compressed, descriptors=(in_d, out_d))
    ...         port2.write(request)
    ...         proto.handle(port, port.read())
    ...         return port2.read()
    ...     return test

Test protocol with different options:

    >>> test = get_test_proto(TestProtocol())
    >>> test((Atom("test"), "value"))
    'value'
    >>> test(Atom("test"))
    'test'

    >>> test = get_test_proto(TestProtocol(), packet=2)
    >>> test((Atom("test"), "value"))
    'value'

    >>> test = get_test_proto(TestProtocol(), packet=4)
    >>> test((Atom("test"), "value"))
    'value'

    >>> test = get_test_proto(TestProtocol(), compressed=True)
    >>> test((Atom("test"), "value"))
    'value'

    >>> test = get_test_proto(TestProtocol(), compressed=9)
    >>> test((Atom("test"), "value"))
    'value'

Some common errors:

    >>> test = get_test_proto(TestProtocol())

    >>> test("unknown")
    (atom(error), atom(badarg))
    >>> test(Atom("unknown"))
    (atom(error), atom(undef))

Exceptions must return type, value and reversed traceback:

    >>> test((Atom("test"), 1, 2)) # doctest: +NORMALIZE_WHITESPACE +ELLIPSIS
    (atom(error), (atom(exception), (atom(exceptions.TypeError),
        'handle_test() takes at most 2 arguments (3 given)',
        [('.../erlproto.py', 73, 'handle', 'response = handler(*args)')])))

    >>> test(Atom("crash")) # doctest: +NORMALIZE_WHITESPACE +ELLIPSIS
    (atom(error), (atom(exception), (atom(exceptions.ValueError), 'error',
        [('<doctest erlproto.txt[3]>', 7, 'handle_crash',
            'raise ValueError("error")'),
        ('.../erlproto.py', 73, 'handle', 'response = handler(*args)')])))
